[package]
name = "mars-rover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
base64 = "0.13.0"
bytes = "1.2.1"
dashmap = "5.4.0"
dyn-clone = "1.0.9"
http = "0.2.8"
http-body = "0.4.5"
hyper = {version="0.14.20", features=["full"]}
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
pin-project = "1.0.12"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tokio ={version= "1.20.1", features=["full"]}
tower = "0.4.13"
tower-http ={version= "0.3.4",features=["decompression-br", "set-header"]}
url = "2.2.2"
